name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 코드가 main 브랜치에 push될 때 작동합니다.

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24.14.1" # 본인이 사용하는 Node.js 버전에 맞게 수정 가능

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # 빌드된 out 폴더를 업로드합니다.

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4